name: '🐧 CI — Coverage'

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '.github/workflows/ci_coverage-linux.yml'
      - 'src/**'
      - 'test/**'
      - 'tools/**'
      - 'package-lock.json'
      - 'package.json'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
    name: Linux
    steps:
      - name: ➕ Actions - Checkout
        uses: actions/checkout@v4

      - name: ➕ Actions - Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: ➕ Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-linux-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-linux-

      - name: 📦 Installing Dependencies
        run: npm ci

      - name: 🧪 Testing
        run: npm test
